# Generated by Django 3.1.6 on 2021-02-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkList', '0003_auto_20210224_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linklist',
            old_name='linkTags',
            new_name='linkTag',
        ),
    ]
