# Generated by Django 3.1.6 on 2021-02-24 13:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkList', '0004_auto_20210224_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linklist',
            old_name='linkTag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='linklist',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='CONTENT'),
        ),
    ]
