# Generated by Django 3.1.6 on 2021-02-11 15:26

from django.db import migrations
import melog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('melog', '0002_auto_20210120_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=melog.fields.ThumbnailImageField(upload_to='photo/%y/%m'),
        ),
    ]
