# Generated by Django 3.1.6 on 2021-02-19 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20210220_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='code', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent',)},
        ),
    ]
