# Generated by Django 3.1.6 on 2021-02-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210220_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_Art', models.ImageField(blank=True, null=True, upload_to='post/%y/%m')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
