# Generated by Django 3.1.6 on 2021-02-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_photoart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoart',
            old_name='photo_Art',
            new_name='image',
        ),
    ]
