# Generated by Django 3.1.6 on 2021-02-24 13:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210220_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='CONTENT'),
        ),
    ]
